<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="pranjal-HP-ProDesk-600-G1-SFF" failures="0" tests="5" name="com.xuriti.api_Auth_Services.TC_6_Invalid_Scenario_SendOTP" time="0.230" errors="0" timestamp="2022-12-22T14:04:36 IST" skipped="0">
  <testcase classname="com.xuriti.api_Auth_Services.TC_6_Invalid_Scenario_SendOTP" name="Invalid_otp" time="0.039"/>
  <system-out/>
  <testcase classname="com.xuriti.api_Auth_Services.TC_6_Invalid_Scenario_SendOTP" name="Invalid_otp" time="0.089"/>
  <system-out/>
  <testcase classname="com.xuriti.api_Auth_Services.TC_6_Invalid_Scenario_SendOTP" name="Invalid_otp" time="0.033"/>
  <system-out/>
  <testcase classname="com.xuriti.api_Auth_Services.TC_6_Invalid_Scenario_SendOTP" name="Invalid_otp" time="0.035"/>
  <system-out/>
  <testcase classname="com.xuriti.api_Auth_Services.TC_6_Invalid_Scenario_SendOTP" name="Invalid_otp" time="0.034"/>
  <system-out/>
</testsuite> <!-- com.xuriti.api_Auth_Services.TC_6_Invalid_Scenario_SendOTP -->
