<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="pranjal-HP-ProDesk-600-G1-SFF" failures="0" tests="5" name="com.xuriti.api_Auth_Services.TC_4_Invalid_Scenario_Sign_In" time="0.240" errors="0" timestamp="2022-12-22T14:04:36 IST" skipped="0">
  <testcase classname="com.xuriti.api_Auth_Services.TC_4_Invalid_Scenario_Sign_In" name="Invalid_data" time="0.038"/>
  <system-out/>
  <testcase classname="com.xuriti.api_Auth_Services.TC_4_Invalid_Scenario_Sign_In" name="Invalid_data" time="0.070"/>
  <system-out/>
  <testcase classname="com.xuriti.api_Auth_Services.TC_4_Invalid_Scenario_Sign_In" name="Invalid_data" time="0.040"/>
  <system-out/>
  <testcase classname="com.xuriti.api_Auth_Services.TC_4_Invalid_Scenario_Sign_In" name="Invalid_data" time="0.045"/>
  <system-out/>
  <testcase classname="com.xuriti.api_Auth_Services.TC_4_Invalid_Scenario_Sign_In" name="Invalid_data" time="0.047"/>
  <system-out/>
</testsuite> <!-- com.xuriti.api_Auth_Services.TC_4_Invalid_Scenario_Sign_In -->
